export default {
  companies: [
    {
      name: 'hellotax',
      period: 'Mar 2019 - Present',
      role: 'Principal Software Engineer (Contractor)',
      intro: `I orchestrated and engineered the front end infrastructure and design for hellotax's new JavaScript-centric app powered by Vue and also managed a co-engineer.`,
      points: [
        'Crafted a 100% custom scalable UI library to enforce consistency and fluency across the application.',
        'Built a multi-role user authentication system from the ground up with JavaScript.',
        'Implemented a client-side localization system for the entire app.',
        'Built a client-side multilingual routing system with solid navigation guards.',
        'Engineered fail-safe optimized utility libraries to minimize runtime errors and unusability in production.',
        'Implemented fast and reliable data transformation and diffing mechanisms on the front end for our data pipelines.',
        'Engineered an overall fast, yet accessible and silky smooth user experience in the app.',
      ],
    },
    {
      name: 'Pixel2HTML',
      period: 'Nov 2018 - Oct 2019',
      role: 'Senior Front End Engineer (Contractor)',
      intro:
        'I worked on a couple of projects for organizations and individuals as a front end engineering contractor.',
      points: [
        'Building front end applications for our several clients. Most especially JavaScript and React applications.',
        'Migrating the company site from HTML/CSS to React/Gatsby.',
        'Crafting and improving design, web accessibility and user experience for clients.',
        'Enforcing healthy codebases, coding style and standards.',
        'Completing projects on time and delivering to clients accordingly.',
        'Communicating constantly with project managers and the team.',
        'Staying up to date with emerging technologies and implementing where necessary.',
      ],
    },
    {
      name: 'Conectar',
      period: 'Jun - Nov 2018',
      role: 'Lead Front End Engineer',
      intro:
        'I led a team of developers through building multiple React applications into a single powerful online learning platform. I also re-engineered and designed several components on the platform.',
      points: [
        'Crafted a solid design system to enforce consistency across the application',
        'Built a messaging system as powerful as Facebook Messenger with React',
        'Built a multi-feature audio and video call application powered by React',
        'Introduced and enforced a consistent coding style across the application',
        'Eliminated dead code which saved us about 20% the size of every page bundle.',
        'Eliminated Bootstrap and several other CSS libraries completely from the application, and replaced them with custom styles.',
        'Reduced bundle size from 5MB to a few kilobytes.',
        'Did a major re-engineering of the development workflow which led to over 70% increase in development compile speed.',
        'Built an appointment scheduling system from the ground up with React.',
      ],
      outro:
        'See the extended list <a target="_blank" rel="noreferrer noopener" href="https://docs.google.com/document/d/1Gw4mcURKddzOJ7OoZsMghJDAhW5zMXler4EeOY9BP6E/edit">here</a>',
    },
  ],
  technologies: [
    'JavaScript',
    'React',
    'CSS-in-JS',
    'Vue.js',
    'Sass',
    'Flux',
    'Flow',
    'NodeJS',
    'ESNext',
    'GraphQL',
    'LessCSS',
    'Next.js',
  ],
  otherProficiencies: [
    'Design Systems',
    'E2E Testing',
    'PWAs',
    'Web Performance',
    'Software Testing',
    'SEO',
    'Git',
    'Accessibility',
    'Webpack',
    'Responsive Web Design',
    'UX Design/Strategy',
  ],
}
