export default {
  companies: [
    {
      name: 'Shopify',
      period: 'May 2020 - Present',
      role: 'Senior Frontend Engineer',
      intro: `Shaping the future of commerce and entrepreneurship – building and advocating for inclusive and thoughtful experiences for over a million merchants across the globe.`,
      points: [
        'Pioneering initiatives around the future of onboarding, signup and developing technical vision for them',
        'Collaborating with UX designers and researchers to inform the direction of products we craft',
        'First-hand involvement in early-stage product and UX thinking and rapid prototyping',
        'Conducting and monitoring several strategic experiments, refining experiences based on resulting metrics and learnings',
        'Participating and incorporating learnings from real merchant interviews and research sessions',
        'Identifying gaps around the org-wide frontend infrastructure, drafting proposals and implementing solutions',
        'Mentoring engineers within and outside my team on best practices, performance and advanced patterns',
        'Providing guidance around product accessibility and inclusivity across the org',
        'Built an OAuth 2.0 compliant client-side library for our Identity provider across Shopify',
      ],
    },
    {
      name: 'hellotax',
      period: 'Mar - Nov 2019',
      role: 'Principal Frontend Engineer (Contractor)',
      intro: `I orchestrated and developed the frontend infrastructure, design and functionality for hellotax's new JavaScript-centric app powered by Vue and also managed a co-engineer.`,
      points: [
        'Crafted a scalable component library that enforced accessibility and fluency across the application.',
        'Built a multi-role user authentication system from the ground up with JavaScript.',
        'Implemented a client-side localization system for the entire app.',
        'Built a client-side multilingual routing system with solid navigation guards.',
        'Engineered fail-safe optimized utility libraries to minimize runtime errors and unusability in production.',
        'Implemented fast and reliable data transformation and diffing mechanisms on the frontend for our data pipelines.',
        'Delivered an overall fast, yet accessible and silky smooth user experience in the app.',
      ],
    },
    {
      name: 'Pixel2HTML',
      period: 'Nov 2018 - Oct 2019',
      role: 'Senior Frontend Engineer (Contractor)',
      intro:
        'I worked on a couple of projects for organizations and individuals as a frontend engineering contractor.',
      points: [
        'Built frontend applications for multiple clients. Most especially JavaScript and React applications.',
        "Rebuilt the company's marketing site initially written in HTML/CSS using React and Gatsby.",
        'Crafted, audited and improved design, accessibility and overall experience of products.',
        'Enforced healthy codebases, coding style and standards.',
        'Completed projects on time and delivered to clients accordingly.',
        'Communicated effectively with project managers and the team.',
      ],
    },
    {
      name: 'MOONDA',
      period: 'Nov 2018 - Jan 2019',
      role: 'Senior Frontend Engineer (Contractor)',
      intro: `I worked with MOONDA as a senior contractor via Pixel2HTML to create the web experience for John Deere's ATU 300 product.`,
      points: [
        'Built a contest application from the ground up using React which enabled users of the product from all around the globe to post photos and share reviews about the product.',
        'Designed and implemented a cross-browser, IE 11 compatible marketing site for the product.',
        'Implemented internationalization on the website with support for over 40 languages.',
        'Implemented automatic locale detection (with proper redirection based on that) and locale-specific content filtering.',
      ],
    },
    {
      name: 'Conectar',
      period: 'Jun - Nov 2018',
      role: 'Lead Frontend Engineer',
      intro:
        'I led a team of developers through building multiple React applications into a single powerful online learning platform. I also re-engineered and designed several components on the platform.',
      points: [
        'Crafted a solid design system to enforce consistency across the application.',
        'Built a messaging system as powerful as Facebook Messenger with React.',
        'Built a multi-feature audio and video call application powered by React.',
        'Introduced and enforced a consistent coding style across the application.',
        'Eliminated dead code which saved us about 20% the size of every page bundle.',
        'Eliminated Bootstrap and other CSS libraries completely from the application, and replaced them with custom styles.',
        'Reduced bundle size from 5MB to a few kilobytes.',
        'Did a major re-engineering of the development workflow which led to over 70% increase in development compile speed.',
        'Built an appointment scheduling system from the ground up with React.',
      ],
      outro:
        'See the extended list <a target="_blank" rel="noreferrer noopener" href="https://docs.google.com/document/d/1Gw4mcURKddzOJ7OoZsMghJDAhW5zMXler4EeOY9BP6E/edit">here.</a>',
    },
    {
      name: 'Pneuma Media',
      period: 'Dec 2013 - Feb 2018',
      role: 'Full Stack Developer',
      intro: `I worked as the only engineer with this company. Built and maintained the backend and frontend of a couple of web apps for clients.`,
      points: [],
    },
  ],
  technologies: [
    'JavaScript',
    'React',
    'CSS-in-JS',
    'TypeScript',
    'Vue.js',
    'Sass',
    'Flux',
    'ESNext',
    'Flow',
    'NodeJS',
    'GraphQL',
    'LessCSS',
    'Next.js',
  ],
  otherProficiencies: [
    'Design Systems',
    'E2E Testing',
    'PWAs',
    'Performance Optimization',
    'Software Testing',
    'SE Optimization',
    'Progressive Enhancement',
    'Accessibility auditing',
    'Build Automation',
    'Responsive Web Design',
    'UX Design/Strategy',
  ],
}
