export default {
  companies: [
    {
      name: 'hellotax',
      period: 'Mar - Nov 2019',
      role: 'Principal Software Engineer (Contractor)',
      intro: `I orchestrated and developed the frontend infrastructure, design and functionality for hellotax's new JavaScript-centric app powered by Vue and also managed a co-engineer.`,
      points: [
        'Crafted a 100% custom scalable component library to enforce consistency and fluency across the application.',
        'Built a multi-role user authentication system from the ground up with JavaScript.',
        'Implemented a client-side localization system for the entire app.',
        'Built a client-side multilingual routing system with solid navigation guards.',
        'Engineered fail-safe optimized utility libraries to minimize runtime errors and unusability in production.',
        'Implemented fast and reliable data transformation and diffing mechanisms on the frontend for our data pipelines.',
        'Delivered an overall fast, yet accessible and silky smooth user experience in the app.',
      ],
    },
    {
      name: 'Pixel2HTML',
      period: 'Nov 2018 - Oct 2019',
      role: 'Senior Frontend Engineer (Contractor)',
      intro:
        'I worked on a couple of projects for organizations and individuals as a frontend engineering contractor.',
      points: [
        'Building frontend applications for our several clients. Most especially JavaScript and React applications.',
        'Migrating the company site from HTML/CSS to React/Gatsby.',
        'Crafting and improving design, web accessibility and user experience for clients.',
        'Enforcing healthy codebases, coding style and standards.',
        'Completing projects on time and delivering to clients accordingly.',
        'Communicating constantly with project managers and the team.',
        'Staying up to date with emerging technologies and implementing where necessary.',
      ],
    },
    {
      name: 'MOONDA',
      period: 'Nov 2018 - Jan 2019',
      role: 'Frontend Engineer (Contractor)',
      intro: `I worked with MOONDA as a senior contractor via Pixel2HTML to create the web experience for John Deere's ATU 300 product.`,
      points: [
        'Built a contest application from the ground up using React which enabled users of the product from all around the globe to post photos and share reviews about the product',
        'Designed and implemented a cross-browser, IE 11 compatible marketing site for the product',
        'Implemented internationalization on the website with support for over 40 languages',
        'Implemented automatic locale detection (with proper redirection based on that) and locale-specific content filtering',
      ],
    },
    {
      name: 'Conectar',
      period: 'Jun - Nov 2018',
      role: 'Lead Frontend Engineer',
      intro:
        'I led a team of developers through building multiple React applications into a single powerful online learning platform. I also re-engineered and designed several components on the platform.',
      points: [
        'Crafted a solid design system to enforce consistency across the application',
        'Built a messaging system as powerful as Facebook Messenger with React',
        'Built a multi-feature audio and video call application powered by React',
        'Introduced and enforced a consistent coding style across the application',
        'Eliminated dead code which saved us about 20% the size of every page bundle.',
        'Eliminated Bootstrap and several other CSS libraries completely from the application, and replaced them with custom styles.',
        'Reduced bundle size from 5MB to a few kilobytes.',
        'Did a major re-engineering of the development workflow which led to over 70% increase in development compile speed.',
        'Built an appointment scheduling system from the ground up with React.',
      ],
      outro:
        'See the extended list <a target="_blank" rel="noreferrer noopener" href="https://docs.google.com/document/d/1Gw4mcURKddzOJ7OoZsMghJDAhW5zMXler4EeOY9BP6E/edit">here.</a>',
    },
    {
      name: 'Pneuma Media',
      period: 'Dec 2013 - Feb 2018',
      role: 'Full Stack Developer',
      intro: `I worked as the only engineer with this company. Built and maintained the backend and frontend of a couple of web apps for clients.`,
      points: [],
    },
  ],
  technologies: [
    'JavaScript',
    'React',
    'CSS-in-JS',
    'TypeScript',
    'Vue.js',
    'Sass',
    'Flux',
    'ESNext',
    'Flow',
    'NodeJS',
    'GraphQL',
    'LessCSS',
    'Next.js',
  ],
  otherProficiencies: [
    'Design Systems',
    'E2E Testing',
    'PWAs',
    'Web Performance',
    'Software Testing',
    'SEO',
    'Progressive Enhancement',
    'Accessibility',
    'Build Automation',
    'Responsive Web Design',
    'UX Design/Strategy',
  ],
}
